# Generated by erl2ex (http://github.com/dazuma/erl2ex)
# From Erlang source: (Unknown source file)
# At: 2022-05-02 12:33:53

defmodule :chumak_lb do
  @typep lb() :: list()

  @spec new() :: lb()

  def new() do
    []
  end

  @spec put(lb(), term()) :: lb()

  def put(lB, item) do
    [item | lB]
  end

  @spec get(lb()) :: :none | {lb(), term()}

  def get([]) do
    :none
  end

  def get([head | tail]) do
    {tail ++ [head], head}
  end

  @spec delete(lb(), term()) :: lb()

  def delete(lB, item) do
    :lists.delete(item, lB)
  end

  @spec is_empty(lb()) :: true | false

  def is_empty([]) do
    true
  end

  def is_empty(_) do
    false
  end

  def to_list(lB) do
    lB
  end
end
